.

diff --git a/.github/workflows/translation.yml b/.github/workflows/translation.yml
--- a/.github/workflows/translation.yml
+++ b/.github/workflows/translation.yml
@@ -66,47 +66,47 @@ jobs:
       #         --file ${{ vars.DOCUMENT_PATH }} \
       #         --sas-token $sas
 
-      - name: 'Translate document to language'
-        run: |
-          set -eux
+      # - name: 'Translate document to language'
+      #   run: |
+      #     set -eux
           
-          end=`date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ'`
-          input_sas=`az storage container generate-sas -n $INPUT_CONTAINER_NAME --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --https-only --permissions lr --expiry $end -o tsv`
-          output_sas=`az storage container generate-sas -n $OUTPUT_CONTAINER_NAME --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --https-only --permissions lw --expiry $end -o tsv`
+      #     end=`date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ'`
+      #     input_sas=`az storage container generate-sas -n $INPUT_CONTAINER_NAME --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --https-only --permissions lr --expiry $end -o tsv`
+      #     output_sas=`az storage container generate-sas -n $OUTPUT_CONTAINER_NAME --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --https-only --permissions lw --expiry $end -o tsv`
 
-          operation_id=$(az rest --method post \
-            --url ${{ secrets.TRANSLATOR_API_URI }}translator/text/batch/v1.0/batches \
-            --headers Ocp-Apim-Subscription-Key=${{ secrets.TRANSLATOR_API_KEY }} \
-            --body "{\"inputs\": [{\"source\": { \"sourceUrl\": \"https://${{ secrets.STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/$INPUT_CONTAINER_NAME?$input_sas\"}, \"targets\": [{\"targetUrl\": \"https://${{ secrets.STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/$OUTPUT_CONTAINER_NAME?$output_sas\",\"language\": \"he\"}]}]}" \
-            --verbose 2> >(grep -i Operation-Location) >/dev/null | grep -oEi '(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}')
-          echo $operation_id
-          echo "operation_id=$operation_id" >> $GITHUB_ENV
-      - name: 'Wait for translation job'
-        run: |
-          action_state="${{ env.action_state }}"
-          echo $action_state
-          status=NotStarted
-          while [ "$status" = "NotStarted" ]
-          do
-            status=$(az rest --method get \
-              --url ${{ secrets.TRANSLATOR_API_URI }}translator/text/batch/v1.0/batches/$operation_id \
-              --headers Ocp-Apim-Subscription-Key=${{ secrets.TRANSLATOR_API_KEY }} | jq -r .status)
-            echo waiting for run to start status is $status
-          done
+      #     operation_id=$(az rest --method post \
+      #       --url ${{ secrets.TRANSLATOR_API_URI }}translator/text/batch/v1.0/batches \
+      #       --headers Ocp-Apim-Subscription-Key=${{ secrets.TRANSLATOR_API_KEY }} \
+      #       --body "{\"inputs\": [{\"source\": { \"sourceUrl\": \"https://${{ secrets.STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/$INPUT_CONTAINER_NAME?$input_sas\"}, \"targets\": [{\"targetUrl\": \"https://${{ secrets.STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/$OUTPUT_CONTAINER_NAME?$output_sas\",\"language\": \"he\"}]}]}" \
+      #       --verbose 2> >(grep -i Operation-Location) >/dev/null | grep -oEi '(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}')
+      #     echo $operation_id
+      #     echo "operation_id=$operation_id" >> $GITHUB_ENV
+      # - name: 'Wait for translation job'
+      #   run: |
+      #     action_state="${{ env.action_state }}"
+      #     echo $action_state
+      #     status=NotStarted
+      #     while [ "$status" = "NotStarted" ]
+      #     do
+      #       status=$(az rest --method get \
+      #         --url ${{ secrets.TRANSLATOR_API_URI }}translator/text/batch/v1.0/batches/$operation_id \
+      #         --headers Ocp-Apim-Subscription-Key=${{ secrets.TRANSLATOR_API_KEY }} | jq -r .status)
+      #       echo waiting for run to start status is $status
+      #     done
 
-          while [ "$status" = "Running" ]
-          do
-            status=$(az rest --method get \
-              --url ${{ secrets.TRANSLATOR_API_URI }}translator/text/batch/v1.0/batches/$operation_id \
-              --headers Ocp-Apim-Subscription-Key=${{ secrets.TRANSLATOR_API_KEY }} | jq -r .status)
-            echo running status is $status
-          done
-          echo status is $status
-          if [ "$status" != "Succeeded" ]
-          then
-            echo "Error!" 1>&2
-            exit 1
-          fi
+      #     while [ "$status" = "Running" ]
+      #     do
+      #       status=$(az rest --method get \
+      #         --url ${{ secrets.TRANSLATOR_API_URI }}translator/text/batch/v1.0/batches/$operation_id \
+      #         --headers Ocp-Apim-Subscription-Key=${{ secrets.TRANSLATOR_API_KEY }} | jq -r .status)
+      #       echo running status is $status
+      #     done
+      #     echo status is $status
+      #     if [ "$status" != "Succeeded" ]
+      #     then
+      #       echo "Error!" 1>&2
+      #       exit 1
+      #     fi
       - uses: actions/checkout@v3
       - name: 'Download translation'
         run: |
